"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta
import cloudinary
from django.core.exceptions import ImproperlyConfigured


# Initialize environment object
env = environ.Env(REDIS_PORT=(int, 6379))
ENVIRONMENT = env.str("ENVIRONMENT", "development")


# Core settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read the .env file
environ.Env.read_env(str(BASE_DIR / ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)


if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    # "django.contrib.admin",  # removing admin panel
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary",
    "cloudinary_storage",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "django_extensions",
    "corsheaders",
    # APPS
    "users",
    "api",
    "realtime",
    "management",
    "courses",
]

ASGI_APPLICATION = "core.asgi.application"


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # corsheaders
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "static"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASE_URL = env("DATABASE_URL", default=env("DATABASE_PUBLIC_URL", default=None))

# Database configuration

import dj_database_url

if ENVIRONMENT == "production":
    DATABASES = {"default": dj_database_url.parse(DATABASE_URL)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [BASE_DIR / "core" / "static"]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ======== CUSTOM SETTINGS ======== #

# Media with cloudinary
IS_CLOUDINARY = env.bool("IS_CLOUDINARY")
if IS_CLOUDINARY:
    SECURE_CONTENT_SECURITY_POLICY = "default-src 'self' https://res.cloudinary.com;"
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": env("CLOUD_NAME"),
        "API_KEY": env("CLOUD_API_KEY"),
        "API_SECRET": env("CLOUD_API_SECRET"),
        # "SIGN_URL": True,
    }
    cloudinary.config(**CLOUDINARY_STORAGE)
    CLOUDINARY_STORAGE_DEFAULT_TYPE = "authenticated"
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

# Redis
ALLOW_REDIS = env.bool("ALLOW_REDIS", default=False)
if ENVIRONMENT == "production" and ALLOW_REDIS:
    REDIS_PASSWORD = env("REDIS_PASSWORD", default="", cast=str)
    REDIS_HOST = env("REDIS_HOST", default="redis", cast=str)
    REDIS_PORT = env.int("REDIS_PORT", default=6379)

    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1",
        }
    }

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [(REDIS_HOST, REDIS_PORT, {"password": REDIS_PASSWORD})],
            },
        }
    }
else:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("127.0.0.1", 6379)],
            },
        },
    }


# Session caching (optional)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# =========== Security Best Practices =============

# HTTPS only cookies
CSRF_COOKIE_SECURE = True
CSRF_FAILURE_VIEW = "utils.csrf.csrf_failure_view"
CORS_ALLOWED_ORIGINS = [
    "https://csss-it-club-portal.up.railway.app",
]
CSRF_TRUSTED_ORIGINS = [
    "https://csss-it-club-portal.up.railway.app",
]

# SESSION_COOKIE_SECURE = True

# # HSTS headers (forces HTTPS)
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# # Force HTTPS redirects
# SECURE_SSL_REDIRECT = True

# # Prevent content sniffing
# SECURE_CONTENT_TYPE_NOSNIFF = True

# # XSS protection
# SECURE_BROWSER_XSS_FILTER = True

# Frame options
# X_FRAME_OPTIONS = "DENY"
AUTHENTICATION_BACKENDS = [
    "users.backends.EmailBackend",
    # "django.contrib.auth.backends.ModelBackend",
]


# RESTAPI
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # simplejwt authentication class
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/min",
        "user": "100/min",
    },
}


# SIMPLE JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Cookie mode
    "AUTH_COOKIE": "access",
    "AUTH_COOKIE_SECURE": True,  # HTTPS only
    "AUTH_COOKIE_HTTP_ONLY": True,  # JS cannot access it
    "AUTH_COOKIE_SAMESITE": "None",  # Required for cross-origin React
    "AUTH_COOKIE_PATH": "/",  # Global cookie
    "AUTH_COOKIE_DOMAIN": None,  # Set domain in production
    "AUTH_COOKIE_REFRESH": "refresh",
    "AUTH_COOKIE_REFRESH_SECURE": True,
    "AUTH_COOKIE_REFRESH_HTTP_ONLY": True,
    "AUTH_COOKIE_REFRESH_SAMESITE": "None",
    "AUTH_COOKIE_REFRESH_PATH": "/",
}

# Custom User model
AUTH_USER_MODEL = "users.User"

# Two fa setting
IS_TWOFA_MANDATORY = env.bool("IS_TWOFA_MANDATORY")

# Cors Headers
CORS_ALLOWED_ORIGINS = [
    "https://csss-it-club-portal.up.railway.app",
]


# Optional: allow credentials like cookies
CORS_ALLOW_CREDENTIALS = True

# Optional: allow all headers and methods
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
    "accept",
    "origin",
    "user-agent",
    "accept-encoding",
    "connection",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

# Profile Max Size
MAX_PROFILE_PIC_SIZE = 10 * 1024 * 1024


# Base URL
BASE_URL = env.str("BASE_URL")

EMAIL = env.str("EMAIL")
