# Generated by Django 6.0.2 on 2026-03-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_allow_proifle_pic_change_setting_allow_profile_pic_change'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Framework',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
